:repo-name: nereon-syntax

== Ribose Specification: Nereon configuration syntax

image:https://travis-ci.com/riboseinc/nereon-syntax.svg?branch=master["Build Status", link="https://travis-ci.com/riboseinc/nereon-syntax"]

== Introduction

This document describes the Nereon configuration syntax used as a method
of input for the Nereon configuration model data structures.

See https://github.com/riboseinc/nereon-models[Nereon configuration models]
for more details.

== Usage

=== General

This specification is built using https://www.metanorma.com[Metanorma].


=== Fetching the document

[source,sh]
----
git clone https://github.com/riboseinc/{repo-name}/
----


=== Installing Build Tools

See the https://www.metanorma.com/overview/getting-started/[Metanorma Quick Start Guide]
for more information.


=== Running via Docker or locally

If you have installed the build tools locally, and wish to run the
locally-installed compilation tools, there is nothing further to set.

If you don't want to deal with local dependencies, use the docker
version by:

[source,sh]
----
export METANORMA_DOCKER=1
----

The `Makefile` will automatically choose the proper command to
execute.


=== Building the document

[source,sh]
----
make clean all
----

The following outputs will be built:

* RSD XML (https://github.com/riboseinc/metanorma-model-rsd) (`[filename].xml`)
* HTML (`[filename].html`)
* PDF (`[filename].pdf`)



=== Iterating the document

[source,sh]
----
make clean all
open *.html
----


== Deployment

The built artifacts are deployed on GitHub pages.
